# 1、基础镜像
FROM nexus.internal:8082/base/server-jre:8u202-alpine

# 2、在构建镜像时，指定镜像的工作目录。之后的命令都是基于此工作目录，不存在则自动创建。
WORKDIR /app/

# 3、复制制品内容到目标目录
COPY ./target/app ./

# 4、容器启动后执行命令
CMD ["sh","/app/bin/startup-logless.sh"]

# 5、健康检查
HEALTHCHECK --interval=30s --timeout=3s --retries=3 \
  CMD curl --fail --silent http://localhost:8888/actuator/health | grep UP || exit 1
