spring:
  profiles: standalone

server:
  port: 1001

eureka:
  instance:
    hostname: localhost
  # 修改Eureka首页上面 System Status 的 Data center 显示信息
  datacenter: SpringCloud
  # 修改Eureka首页上面 System Status 的 Environment 显示信息
  environment: local
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: false
  client:
    # 是否要注册到其他Eureka Server实例
    register-with-eureka: false
    # 是否要从其他Eureka Server实例获取数据
    fetch-registry: false
    serviceUrl:
      # 相互注册，组成一个集群，实现高可用
      defaultZone: http://localhost:${server.port}/eureka/


