mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: site.mingsha.cicd.dal.model
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-prefix: executableSql.
